---
resources:
  - name: config-server-repo
    type: git
    source:
      uri: https://github.com/metflix/config-server
      branch: master
  - name: eureka-server-repo
    type: git
    source:
      uri: https://github.com/metflix/eureka-server
      branch: master
  - name: hystrix-dashboard-repo
    type: git
    source:
      uri: https://github.com/metflix/hystrix-dashboard
      branch: master
  - name: membership-repo
    type: git
    source:
      uri: https://github.com/metflix/membership
      branch: master
  - name: recommendations-repo
    type: git
    source:
      uri: https://github.com/metflix/recommendations
      branch: master
  - name: ui-repo
    type: git
    source:
      uri: https://github.com/metflix/ui
      branch: master
  - name: metflix-repo
    type: git
    source:
      uri: https://github.com/metflix/metflix
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: {{docker-repo}}
      username: {{docker-username}}
      password: {{docker-password}}  
      email: {{docker-email}}  

jobs:
  - name: config-server-unit
    serial: true
    plan:
      - get: config-server-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: config-server-deploy
    plan:
      - get: config-server-repo
        trigger: true
        passed: [ config-server-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - -c
            - |
              cd config-server-repo
              ./mvnw package -Dmaven.test.skip=true -Dmaven.repo.local=../m2/rootfs/opt/m2
              cp target/*.jar ../output/app.jar
      - put: cf
        params:
          manifest: config-server-repo/manifest.yml
          path: output/app.jar
          current_app_name: config-server
  - name: eureka-server-unit
    plan:
      - get: eureka-server-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: hystrix-dashboard-unit
    plan:
      - get: hystrix-dashboard-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: hystrix-dashboard-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: membership-unit
    plan:
      - get: membership-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: membership-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: recommendations-unit
    plan:
      - get: recommendations-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: recommendations-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: ui-unit
    plan:
      - get: ui-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: ui-repo
              path: repo
            - name: m2  
          run:
            path: sh
            args: 
            - repo/ci/tasks/unit.sh
  - name: init-m2
    plan:
      - get: metflix-repo
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: metflix-repo
              path: repo
          outputs:
            - name: to-push  
          run:
            path: sh 
            args: 
            - repo/ci/tasks/m2.sh
            - init
      - put: m2
        params:
          import_file: to-push/rootfs.tar

  - name: update-m2
    plan:
      - get: metflix-repo
      - get: m2
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: metflix-repo
              path: repo
            - name: m2
          outputs:
            - name: to-push    
          run:
            path: sh
            args: 
            - repo/ci/tasks/m2.sh
      - put: m2
        params:
          import_file: to-push/rootfs.tar