---
resources:
  - name: config-server-repo
    type: git
    source:
      uri: https://github.com/metflix/config-server
      branch: master
  - name: eureka-server-repo
    type: git
    source:
      uri: https://github.com/metflix/eureka-server
      branch: master
  - name: hystrix-dashboard-repo
    type: git
    source:
      uri: https://github.com/metflix/hystrix-dashboard
      branch: master
  - name: membership-repo
    type: git
    source:
      uri: https://github.com/metflix/membership
      branch: master
  - name: recommendations-repo
    type: git
    source:
      uri: https://github.com/metflix/recommendations
      branch: master
  - name: ui-repo
    type: git
    source:
      uri: https://github.com/metflix/ui
      branch: master
  - name: metflix-repo
    type: git
    source:
      uri: https://github.com/metflix/metflix
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: {{docker-repo}}
      username: {{docker-username}}
      password: {{docker-password}}  
      email: {{docker-email}}  

jobs:
  - name: config-server-unit
    serial: true
    plan:
      - get: config-server-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
              path: repo
            - name: metflix-repo
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: config-server-deploy
    plan:
      - get: config-server-repo
        trigger: true
        passed: [ config-server-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: config-server-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: config-server-repo/manifest.yml
          path: output/app.jar
          current_app_name: config-server-metflix

  - name: config-server-create-service
    plan:
      - task: create-service
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
          run:
            path: sh
            args: 
            - -c 
            - | 
              cf login -a {{cf-api}} -u {{cf-username}} -p {{cf-password}} -o {{cf-org}} -s {{cf-space}}
              cf create-user-provided-service config-server -p '{"uri":"http://config-server-metflix.cfapps.io"}'

  - name: eureka-server-unit
    plan:
      - get: eureka-server-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: metflix-repo
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: eureka-server-deploy
    plan:
      - get: eureka-server-repo
        trigger: true
        passed: [ eureka-server-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: eureka-server-repo/manifest.yml
          path: output/app.jar
          current_app_name: eureka-server-metflix

  - name: eureka-server-create-service
    plan:
      - task: create-service
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
          run:
            path: sh
            args: 
            - -c 
            - | 
              cf login -a {{cf-api}} -u {{cf-username}} -p {{cf-password}} -o {{cf-org}} -s {{cf-space}}
              cf create-user-provided-service eureka-server -p '{"uri":"http://eureka-server-metflix.cfapps.io"}'
  - name: hystrix-dashboard-unit
    plan:
      - get: hystrix-dashboard-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: hystrix-dashboard-repo
              path: repo
            - name: metflix-repo
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: hystrix-dashboard-deploy
    plan:
      - get: hystrix-dashboard-repo
        trigger: true
        passed: [ hystrix-dashboard-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: hystrix-dashboard-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: hystrix-dashboard-repo/manifest.yml
          path: output/app.jar
          current_app_name: hystrix-dashboard-metflix
  - name: membership-unit
    plan:
      - get: membership-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: membership-repo
              path: repo
            - name: metflix-repo              
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: membership-deploy
    plan:
      - get: membership-repo
        trigger: true
        passed: [ membership-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: membership-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: membership-repo/manifest.yml
          path: output/app.jar
          current_app_name: membership-metflix
  - name: recommendations-unit
    plan:
      - get: recommendations-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: recommendations-repo
              path: repo
            - name: metflix-repo
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: recommendations-deploy
    plan:
      - get: recommendations-repo
        trigger: true
        passed: [ recommendations-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: recommendations-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: recommendations-repo/manifest.yml
          path: output/app.jar
          current_app_name: recommendations-metflix
  - name: ui-unit
    plan:
      - get: ui-repo
        trigger: true
      - get: metflix-repo
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: ui-repo
              path: repo
            - name: metflix-repo
            - name: m2  
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/unit.sh
  - name: ui-deploy
    plan:
      - get: ui-repo
        trigger: true
        passed: [ ui-unit ]
      - get: metflix-repo
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: ui-repo
              path: repo
            - name: metflix-repo
            - name: m2 
          outputs:
            - name: output 
          run:
            path: sh
            args: 
            - metflix-repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: ui-repo/manifest.yml
          path: output/app.jar
          current_app_name: ui-metflix

  - name: init-m2
    plan:
      - get: metflix-repo
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: metflix-repo
              path: repo
          outputs:
            - name: to-push  
          run:
            path: sh 
            args: 
            - repo/ci/tasks/m2.sh
            - init
      - put: m2
        params:
          import_file: to-push/rootfs.tar

  - name: update-m2
    plan:
      - get: metflix-repo
      - get: m2
      - task: build-m2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine 
          inputs:
            - name: metflix-repo
              path: repo
            - name: m2
          outputs:
            - name: to-push    
          run:
            path: sh
            args: 
            - repo/ci/tasks/m2.sh
      - put: m2
        params:
          import_file: to-push/rootfs.tar

groups:
  - name: all
    jobs:
    - init-m2
    - update-m2
    - config-server-unit
    - config-server-deploy
    - config-server-create-service
    - eureka-server-unit
    - eureka-server-deploy
    - eureka-server-create-service
    - hystrix-dashboard-unit
    - hystrix-dashboard-deploy
    - membership-unit
    - membership-deploy
    - recommendations-unit
    - recommendations-deploy
    - ui-unit
    - ui-deploy
  - name: m2
    jobs:
    - init-m2
    - update-m2
  - name: config-server
    jobs:
    - config-server-unit
    - config-server-deploy
    - config-server-create-service
  - name: eureka-server
    jobs:
    - eureka-server-unit
    - eureka-server-deploy
    - eureka-server-create-service
  - name: hystrix-dashboard
    jobs:
    - hystrix-dashboard-unit
    - hystrix-dashboard-deploy
  - name: membership
    jobs:
    - membership-unit
    - membership-deploy
  - name: recommendations
    jobs:
    - recommendations-unit
    - recommendations-deploy
  - name: ui
    jobs:
    - ui-unit
    - ui-deploy
